### ISSUE TITLE
Add CI testing

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#11]
### User Story
Ideally the code will be linted for formatting (rules to be discussed with designers) and automatically tested to ensure it will work properly. Basically reviews should be to make sure the code is good and it does what it should, but it should be tested so we at least know it works with no errors

### Tasks
- [ ] Check for extra whitespace

**Comment by kungharrison** [comment]
@HoldenA1 Maybe create a list of all the tests we want here first so we can track the progress of the linter

**Comment by HoldenA1** [comment]
Sounds good. I'll edit the comment to include things it would be good to test for.
