### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#12]
### User Story
Developers need to visualize the websites they are creating.

### Tasks
- [ ] Suggestion Page
- [ ] Feedback from user interaction

**Comment by thomasrexin** [comment]
@kungharrison I made a miro board for the wire frames (https://miro.com/app/board/uXjVPG5rCMw=/). Let me know if there is any other screens I should add or any edits. I haven't changed any of the style or colors yet but I can after all the wireframes are added if you want.

**Comment by kungharrison** [comment]
@thomasrexin Looks good so far, I'll let you know if we need anything else

**Comment by thomasrexin** [comment]
@kungharrison should I link it in the issues where it is relevant for the other devs?

**Comment by kungharrison** [comment]
@thomasrexin Yeah, it might be best to export them as images from Miro and to add them to the other issues

**Comment by kungharrison** [comment]
Added to user story
