### ISSUE TITLE
Update & Create User Stories

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#13]
### User Story
Developers need more specified and bite-sized user stories to tackle in the future. Also needs to be updated with more specific instructions.

### Tasks
- [x] Update user stories in In Progress
- [x] Create and update user stories in Approved

**Comment by kungharrison** [comment]
@number000000 Make a wireframe for list of classes

**Comment by number000000** [comment]
> @number000000 Make a wireframe for list of classes

I made the wireframe and added it to the user story. Let me know if I should change anything!

**Comment by kungharrison** [comment]
@number000000 Looks good!
